name: Spring Boot CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # # Step: SonarQube analysis
      # - name: SonarQube Scan
      #   uses: SonarSource/sonarcloud-github-action@v2
      #   with:
      #     entryPoint: .
      #   env:
      #     SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      #     SONAR_PROJECT_KEY: ${{ secrets.SONAR_PROJECT_KEY }}
      #     SONAR_ORGANIZATION: ${{ secrets.SONAR_ORGANIZATION }}

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: DockerHub login
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/springboot-hello-k8s:1.0 .

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/springboot-hello-k8s:1.0

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'v1.30.0'

      # - name: Configure kubeconfig
      #   run: |
      #     mkdir -p ~/.kube
      #     echo "${{ secrets.KUBECONFIG_CONTENT }}" > ~/.kube/config

      # - name: Deploy to Kubernetes
      #   run: |
      #     kubectl apply -f deployment.yaml
      #     kubectl apply -f service.yaml
